//
// WorkoutSummaryFormatter.swift
// Medina
//
// Created: November 13, 2025
// Purpose: Format workout summaries as shareable text
//

import Foundation

class WorkoutSummaryFormatter {

    /// Generate formatted text summary for sharing
    static func formatForSharing(summary: CompletedWorkoutSummary) -> String {
        var text = ""

        // Header
        text += "Workout Summary: \(summary.workoutName)\n"
        text += "Date: \(formatDate(summary.scheduledDate))\n"
        text += "Duration: \(formatDuration(summary.duration.actual))/\(formatDuration(summary.duration.estimated)) (\(summary.duration.formattedPercentage))\n"
        text += "\n"

        // Summary metrics (percentage funnel)
        text += "PERFORMANCE\n"
        text += "Duration: \(formatDuration(summary.duration.actual))/\(formatDuration(summary.duration.estimated)) (\(summary.duration.formattedPercentage))\n"
        text += "Exercises: \(summary.exercises.completed)/\(summary.exercises.total) (\(summary.exercises.formattedPercentage))\n"
        text += "Sets: \(summary.sets.completed)/\(summary.sets.total) (\(summary.sets.formattedPercentage))\n"
        text += "Reps: \(summary.reps.completed)/\(summary.reps.total) (\(summary.reps.formattedPercentage))\n"
        text += "Volume: \(formatVolume(summary.volume.actual))/\(formatVolume(summary.volume.target)) (\(summary.volume.formattedPercentage))\n"
        text += "\n"

        // Exercises breakdown
        text += "EXERCISES (\(summary.exercises.completed)/\(summary.exercises.total))\n"
        for exercise in summary.exerciseDetails {
            let statusIcon = exercise.status == .completed ? "✓" : "⊘"
            let label = exercise.supersetLabel ?? ""
            let name = label.isEmpty ? exercise.exerciseName : "\(label). \(exercise.exerciseName)"

            if exercise.status == .completed {
                let volume = formatVolume(exercise.totalVolume)
                text += "\(statusIcon) \(name)\n"
                text += "   \(exercise.setsCompleted)/\(exercise.setsTotal) sets • \(exercise.totalReps) reps • \(volume)\n"
            } else {
                text += "\(statusIcon) \(name) - Skipped\n"
            }
        }

        text += "\n"
        text += "Generated by Medina"

        return text
    }

    // MARK: - Helper Formatters

    private static func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return formatter.string(from: date)
    }

    private static func formatDuration(_ duration: TimeInterval) -> String {
        let minutes = Int(duration) / 60
        if minutes < 60 {
            return "\(minutes) min"
        } else {
            let hours = minutes / 60
            let remainingMinutes = minutes % 60
            return "\(hours) hr \(remainingMinutes) min"
        }
    }

    private static func formatVolume(_ volume: Double) -> String {
        if volume == 0 {
            return "0 lbs (bodyweight)"
        }
        return "\(Int(volume.rounded())) lbs"
    }
}
